### ISSUE TITLE
Multi drive support

### ISSUE THREAD

**Issue by SkyeErnst** [zzzz465/Rimworld-automatic-mod-sorter#7]
It looks like the mods folder location is derived from the modconfig file location. Due to this, cases where the game is installed on a drive that isn't C (like in my case), it fails to find the mods folder.

Possible workaround is using symlink junctions, but it might just be easier to let the user browse for the mods folder location.

**Comment by zzzz465** [comment]
download v0.56 version and test it.
if it works, please leave a comment below.

**Comment by SkyeErnst** [comment]
v0.56 works!
